### ISSUE TITLE
Migration does not work when invoking compiled code with node

### ISSUE THREAD

**Issue by jurna** [mycodeself/mongo-migrate-ts#11]
When you compile the project ant try tu run it using command `node build/migrations/index up` migration fails with error:
```
Migrations up/home/projects/dist/migrations/20200326_01.d.ts:1
import { MigrationInterface } from 'mongo-migrate-ts';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1063:16)
    at Module._compile (internal/modules/cjs/loader.js:1111:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at /home/danielius/projects/efi/git/efi-fatca/node_modules/mongo-migrate-ts/dist/lib/migrations.js:27:69
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.exports.loadMigrationFile (/home/danielius/projects/efi/git/efi-fatca/node_modules/mongo-migrate-ts/dist/lib/migrations.js:27:21)
```
The issue is that node tryes to load *.ts files found in migration diretory and fails. It should load only *.js files

**Comment by mycodeself** [comment]
Hi, thank you for your feedback.

I made a new release 1.0.8 with a fix, now it will detect when is running under ts-node and when is runnming with node for load the correct file extensions.

Can you test and tell me if its working for you or not??

Thanks a lot!

**Comment by jurna** [comment]
Yes, it works fine with 1.0.8 version. Thanks.
