### ISSUE TITLE
ERR_REQUIRE_ESM after installing globally

### ISSUE THREAD

**Issue by Krispy2009** [mycodeself/mongo-migrate-ts#53]
Hi, I've installed the package using `npm install -g mongo-migrate-ts` according to the instructions, but when I try to run the CLI using `mongo-migrate` I get:
```
internal/modules/cjs/loader.js:1015
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /opt/homebrew/lib/node_modules/mongo-migrate-ts/node_modules/ora/index.js
require() of ES modules is not supported.
require() of /opt/homebrew/lib/node_modules/mongo-migrate-ts/node_modules/ora/index.js from /opt/homebrew/lib/node_modules/mongo-migrate-ts/dist/lib/commands/down.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /opt/homebrew/lib/node_modules/mongo-migrate-ts/node_modules/ora/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1015:13)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/opt/homebrew/lib/node_modules/mongo-migrate-ts/dist/lib/commands/down.js:7:31)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14) {
  code: 'ERR_REQUIRE_ESM'
}
```

I tried both on node `v14.18.2` and `v12.22.10` installed via homebrew on an M1 mac

Is this a known issue, or is this something I've messed up on my side?

**Comment by mycodeself** [comment]
Hi, seems a problem related to the latest version of the `ora` package after I did a upgrade of all the dependencies in the last release. 

I'll try to solve it asap, until then I recommend you use the previous version!

**Comment by mycodeself** [comment]
@Krispy2009 I've fixed this in the latest release, let me know if you have any issue!

**Comment by Krispy2009** [comment]
@mycodeself Thanks for the super speedy fix!
